config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  root 'prototypes#index'
  resources :newests, only: :index
  resources :users, only: :show
  resources :tags, only: [:index, :show]
  resources :prototypes, except: :index do
    resources :comments, only: :create
    resources :likes, only: [:create, :destroy]
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :prototype

  validates :content, presence: true
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :prototype, counter_cache: :like_count
end

app/models/prototype.rb
class Prototype < ActiveRecord::Base
  belongs_to :user
  has_many :comments, dependent: :delete_all
  has_many :thumbnails, dependent: :delete_all
  has_many :likes
  accepts_nested_attributes_for :thumbnails, reject_if: proc { |attributes| attributes[:thumbnail].blank? }

  validates :title, :catch_copy, :concept, :thumbnails, presence: true

  acts_as_taggable
end

app/models/thumbnail.rb
class Thumbnail < ActiveRecord::Base
  belongs_to :prototype

  mount_uploader :thumbnail, ImageUploader

  enum status: [:main, :sub]
  # validates :thumbnail, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :prototypes
  has_many :comments
  has_many :likes

  mount_uploader :avatar, ImageUploader

  validates :name, :profile, :position, :occupation, :avatar, presence: true

  def update_without_current_password(params, *options)
    params.delete(:current_password)

    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end

    result = update_attributes(params, *options)
    clean_up_passwords
    result
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!


  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :password, :profile, :position, :occupation, :avatar) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :password, :profile, :position, :occupation, :avatar) }
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    current_user.comments.create(create_params)
    @comments = Comment.where(prototype_id: params[:prototype_id])
  end

private
  def create_params
    params.permit(:content, :prototype_id)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    @prototype = Prototype.find(params[:prototype_id])
    current_user.likes.create(create_params)
    @like = set_like
    set_likes
  end

  def destroy
    @prototype = Prototype.find(params[:prototype_id])
    Like.destroy(set_like)
    set_likes
  end

  private
  def create_params
    params.permit(:prototype_id)
  end

  def set_like
    Like.where(user_id: current_user.id, prototype_id: params[:prototype_id])
  end

  def set_likes
    @likes = Like.where(prototype_id: params[:prototype_id]).count
  end

end

app/controllers/newests_controller.rb
class NewestsController < ApplicationController
  def index
    @prototypes = Prototype.page(params[:page]).per(5).order('created_at DESC').includes(:user)
    render 'prototypes/index'
  end
end

app/controllers/prototypes_controller.rb
class PrototypesController < ApplicationController
  def index
    @prototypes = Prototype.page(params[:page]).per(5).order('like_count DESC').includes(:user)
  end

  def show
    @prototype = Prototype.find(params[:id])
    @comments = Comment.where(prototype_id: params[:id]).includes(:user)
    @likes = Like.where(prototype_id: params[:id]).count
    @like = Like.where(user_id: current_user.id, prototype_id: params[:id])
  end

  def new
    @prototype = Prototype.new
    @prototype.thumbnails.build
  end

  def create
    @prototype = current_user.prototypes.new(prototype_params)
    if @prototype.save
      redirect_to root_path
    else
      @prototype.thumbnails.build
      @prototype.valid?
      flash.now[:alert] = 'Not Input'
      render :new
    end
  end

  def edit
    @prototype = Prototype.find(params[:id])
  end

  def update
    @prototype = Prototype.find(params[:id])
    @prototype.update(prototype_params)
    redirect_to :root
  end

  def destroy
    Prototype.find(params[:id]).destroy
    redirect_to :root
  end

  private
  def prototype_params
    params.require(:prototype).permit(:title, :catch_copy, :concept, thumbnails_attributes: [:id, :thumbnail, :status]).merge(tag_list: params[:prototype][:tag])
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected
  def update_resource(resource, params)
    resource.update_without_current_password(params)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = ActsAsTaggableOn::Tag.most_used
  end

  def show
    @tag = ActsAsTaggableOn::Tag.find(params[:id])
    @prototypes = Prototype.tagged_with(@tag.name).page(params[:page]).per(5).includes(:user)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @prototypes = Prototype.where(user_id: params[:id]).page(params[:page]).per(5).includes(:user, :tags, :tags, :tag_taggings)
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/comments/create.js.erb
$('#content').val('');
$('.comment_content').html("<%= j(render partial: 'prototypes/comment', collection: @comments) %>");
$('.num').html("<%= @comments.size %>");

app/views/layouts/_footer.html.haml
.container
  %footer
    %p &copy; PROTO SPACE 2015.
  

app/views/layouts/_header.html.haml
.navbar.navbar-default.navbar-static-top.navbar-fixed-top
  .container
    %button.navbar-toggle(type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse")
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    %a.navbar-brand(href="/")
      = image_tag('logo.png', alt: 'PROTO TYPE - SHARE THE PROTOTYPE', height: '36px')
    .navbar-collapse.collapse.navbar-responsive-collapse
      //not login
      - unless user_signed_in?
        %ul.nav.navbar-nav.navbar-right
          %li
            .btn.btn-primary.navbar-btn
              = link_to 'Get Started', user_session_path

      //login
      %ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          %li.dropdown
            = link_to '#', class: 'dropdown-toggle', aria: { expanded: false }, data: { toggle: 'dropdown' } do
              = current_user.name
              %span.caret
              %ul.dropdown-menu{ role: 'menu' }
                %li
                  = link_to 'My Page', user_path(current_user)
                %li
                  = link_to 'Profile Edit', edit_user_registration_path
                %li
                  = link_to 'Logout', destroy_user_session_path, method: :delete
          %li
          .btn.btn-primary.navbar-btn.btn-lg
            = link_to 'New Proto', new_prototype_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{ content: 'text/html charset: US-ASCII', http: { equiv: 'Content-Type' } }/
    %title Protospace
    = stylesheet_link_tag    'application', media: 'all', data: { turbolinks: { track: true }}
    = javascript_include_tag 'application', data: { turbolinks: { track: true }}
    = csrf_meta_tags
  %body
    = render "layouts/header"
    = yield
    = render "layouts/footer"

app/views/likes/create.js.erb
$('.like_button').html("<%= j(render partial: 'prototypes/like') %>");

app/views/likes/destroy.js.erb
$('.like_button').html("<%= j(render partial: 'prototypes/like') %>");

app/views/proto/show.html.haml
.container.proto-page
  %header.row.user-nav
    -# ユーザー情報
    .col-md-6
      .media
        .media-left
          = image_tag(current_user.avatar.url, alt: '64x64', data: { holder: { rendered: 'true' }}, class: 'media-object', style: 'width: 64px; height: 64px;')

        .media-body
          %h4#top-aligned-media.media-heading
            = @prototype.title
          .proto-user
            = link_to current_user.name, "/users/#{current_user.id}"
            %span.degree= current_user.profile

    -# LIKE
    .col-md-6.text-right
      %button.btn.btn-default
        = image_tag("icon_heart.svg")
        Like
        %span.num 20
  -# main画像
  .row
    .col-md-9
      = image_tag(@prototype.thumbnails.first.thumbnail.url, class: 'img-responsive', style: 'margin: 0 auto')
    -# sub画像
    .col-md-3
      %ul.proto-sub-list.list-group
        - @prototype.thumbnails.each do |sub_thumbnail|
          - if sub_thumbnail.status == "sub"
            %li.list-group-item
              = image_tag(sub_thumbnail.thumbnail.url, class: 'img-responsive')
  -# プロトタイプinfo
  .row.proto-description
    .col-md-3
      %h4 Catch Copy
      %p= @prototype.catch_copy
    .col-md-6
      %h4 Concept
      %p= @prototype.concept
    .col-md-3
      %h4 Tag List
      %ul.proto-tag-list.list-inline
        %li
          .btn.btn-default= link_to 'iPad', '#'
        %li
          .btn.btn-default= link_to 'wireframe', '#'
  -# comment
  .row.proto-comments
    %h4.col-md-12
      Comments
      %span.num (10)
    .col-md-8
      .media
        .media-left

app/views/prototypes/_comment.html.haml
= image_tag(comment.user.avatar.url, class: 'user_thumbnail')
%strong= comment.user.name
%span.cmt= comment.content
%br

app/views/prototypes/_like.html.haml
- if @like.blank?
  = button_tag class: 'btn btn-default' do
    = link_to prototype_likes_path(@prototype), method: :post, remote: true do
      = image_tag('icon_heart.svg')
      Like
      %span.num= @likes
- else
  = button_tag class: 'btn btn-danger' do
    = link_to prototype_like_path(@prototype, @like), method: :delete, remote: true do
      = image_tag('icon_heart.svg')
      Like
      %span.num= @likes

app/views/prototypes/_prototype.html.haml
.col-sm-4.col-md-3.proto-content.prototype
  .thumbnail
    - if user_signed_in? && current_user.id == prototype.user_id
      .user_operation
        %ul.operation_list
          %li
            = link_to 'edit', edit_prototype_path(prototype)
          %li
            = link_to 'delete', prototype_path(prototype), method: :delete
    = link_to image_tag(prototype.thumbnails.first.thumbnail.url), prototype_path(prototype)
    .caption
      %h3= prototype.title
      .proto-meta
        .proto-user
          = link_to prototype.user.name, user_path(prototype.user)
        .proto-posted
          = prototype.created_at.strftime('%b %d')
      %ul.proto-tag-list.list-inline
        - prototype.tags.each do |tag|
          %li
            .btn.btn-default= link_to tag.name, tag_path(tag)

app/views/prototypes/_sort.html.haml
.filter-nav
  .container
    .row
      %ul.nav.nav-pills.col-lg-11
        %li{ role: 'presentation', class: "#{'active' if controller.controller_name == 'prototypes'}" }
          = link_to 'Popular PROTO', root_path
        %li{ role: 'presentation', class: "#{'active' if controller.controller_name == 'newests'}" }
          = link_to 'Newest PROTO', newests_path
      = button_tag class: 'btn btn-default col-lg-1' do
        = link_to 'View Tags', tags_path

app/views/prototypes/_tag.html.haml
%li
  .btn.btn-default= link_to tag.name, tags_path

app/views/prototypes/edit.html.haml
%h1= @thumbnail
= form_for @prototype do |f|
  .container.proto-new
    .col-md-8.col-md-offset-2
      %header.row.user-nav.row
        .col-md-12
          .proto-new-title= f.text_field :title, placeholder: "Title #{flash[:alert]}", autocomplete: 'off'
        .row
          .col-md-12
            .cover-image-upload
              = image_tag(@prototype.thumbnails.first.thumbnail.url, id: 'main_thumbnail')
              = f.fields_for :thumbnails, @prototype.thumbnails[0] do |thumbnails_f|
                = thumbnails_f.file_field :thumbnail, accept: 'image/*', onchange: "openFile(event, 'main')"
          .col-md-12
            %ul.proto-sub-list.list-group
              %li.list-group-item.col-md-4
                .image-upload
                  = image_tag(@prototype.thumbnails.second.thumbnail.url, id: 'sub_thumbnail1') if @prototype.thumbnails.second.present?
                  = f.fields_for :thumbnails, @prototype.thumbnails[1] do |thumbnails_f|
                    = thumbnails_f.file_field :thumbnail, accept: 'image/*', onchange: "openFile(event, 'sub_thumbnail1')"
              %li.list-group-item.col-md-4
                .image-upload
                  = image_tag(@prototype.thumbnails.third.thumbnail.url, id: 'sub_thumbnail2') if @prototype.thumbnails.third.present?
                  = f.fields_for :thumbnails, @prototype.thumbnails[2] do |thumbnails_f|
                    = thumbnails_f.file_field :thumbnail, accept: 'image/*', onchange: "openFile(event, 'sub_thumbnail2')"
              %li.list-group-item.col-md-4
                .image-upload-plus
                  %span +
        .row.proto-description
          .col-md-12
            = f.text_field :catch_copy, placeholder: "Catch Copy #{flash[:alert]}", autocomplete: 'off', maxlength: '255'
            = f.text_area :concept, placeholder: "Concept #{flash[:alert]}", cols: '30', rows: '4', autocomplete: 'off', maxlength: '255'
          .col-md-12
            %h4 Tag List
            .row
              .col-md-3
                = text_field_tag 'prototype[tag][]', '', placeholder: 'Web Design'
              .col-md-3
                = text_field_tag 'prototype[tag][]', '', placeholder: 'UI'
              .col-md-3
                = text_field_tag 'prototype[tag][]', '', placeholder: 'Application'
        .row.text-center.proto-btn
          = f.submit 'Publish', class: 'btn btn-lg btn-primary btn-block'

app/views/prototypes/index.html.haml
.jumbotron
  .container.text-center
    = image_tag("header_logo.png", alt: 'PROTO TYPE - SHARE THE PROTOTYPE', height: '73px')

= render partial: 'prototypes/sort'

#prototypes
  .container
    .row
      .page
        = render @prototypes

= paginate @prototypes

app/views/prototypes/index.js.erb
$('#prototypes').append("<div class='page'><%= escope_javascript(render partial: 'prototype', collection: @prototypes) %></div>");

app/views/prototypes/new.html.haml
= form_for @prototype do |f|
  .container.proto-new
    .col-md-8.col-md-offset-2
      %header.row.user-nav.row
        .col-md-12
          .proto-new-title= f.text_field :title, placeholder: "Title #{flash[:alert]}", autofocus: true, autocomplete: 'off'
        -# main画像
        .row
          .col-md-12
            .cover-image-upload
              = image_tag('', id: 'main_thumbnail')
              = f.fields_for :thumbnails do |thumbnails_f|
                = thumbnails_f.hidden_field :status, value: "main"
                = thumbnails_f.file_field :thumbnail, accept: 'image/*', onchange: "openFile(event, 'main')"

            -# sub画像
            %ul.proto-sub-list.list-group
              %li.list-group-item.col-md-4
                .image-upload
                  = image_tag('', id: 'sub_thumbnail1')
                  = f.fields_for :thumbnails do |thumbnails_f|
                    = thumbnails_f.hidden_field :status, value: "sub"
                    = thumbnails_f.file_field :thumbnail, accept: 'image/*', onchange: "openFile(event, 'sub_thumbnail1')"
              -# sub画像
              %li.list-group-item.col-md-4
                .image-upload
                  = image_tag('', id: 'sub_thumbnail2')
                  = f.fields_for :thumbnails do |thumbnails_f|
                    = thumbnails_f.hidden_field :status, value: "sub"
                    = thumbnails_f.file_field :thumbnail, accept: 'image/*', onchange: "openFile(event, 'sub_thumbnail2')"
              -# sub画像
              %li.list-group-item.col-md-4
                .image-upload-plus
                  %span +
                .image-upload.do_not_show
                  = image_tag('', id: 'sub_thumbnail3')
                  = f.fields_for :thumbnails do |thumbnails_f|
                    = thumbnails_f.hidden_field :status, value: "sub"
                    = thumbnails_f.file_field :thumbnail, accept: 'image/*', onchange: "openFile(event, 'sub_thumbnail3')"

        .row.proto-description
          .col-md-12
            = f.text_field :catch_copy, placeholder: "Catch Copy #{flash[:alert]}", autocomplete: 'off', maxlength: '255'
            = f.text_area :concept, placeholder: "Concept #{flash[:alert]}", cols: '30', rows: '4', autocomplete: 'off', maxlength: '255'
          .col-md-12
            %h4 Tag List
            .row
              .col-md-3
                = text_field_tag 'prototype[tag][]', '', placeholder: 'Web Design'
              .col-md-3
                = text_field_tag 'prototype[tag][]', '', placeholder: 'UI'
              .col-md-3
                = text_field_tag 'prototype[tag][]', '', placeholder: 'Application'
        .row.text-center.proto-btn
          = f.submit 'Publish', class: 'btn btn-lg btn-primary btn-block'

app/views/prototypes/show.html.haml
.container.proto-page
  %header.row.user-nav
    -# ユーザー情報
    .col-md-6
      .media
        .media-left
          = image_tag(current_user.avatar.url, alt: '64x64', data: { holder: { rendered: 'true' }}, class: 'media-object', style: 'width: 64px; height: 64px;')

        .media-body
          %h4#top-aligned-media.media-heading
            = @prototype.title
          .proto-user
            by
            = link_to @prototype.user.name, user_path(@prototype.user)
            %span.degree= @prototype.user.profile

    -# LIKE
    .col-md-6.text-right.like_button
      = render partial: 'prototypes/like'

  -# main画像
  .row
    .col-md-9
      = image_tag(@prototype.thumbnails.first.thumbnail.url, class: 'img-responsive', style: 'margin: 0 auto')
    -# sub画像
    .col-md-3
      %ul.proto-sub-list.list-group
        - @prototype.thumbnails.each do |sub_thumbnail|
          - if sub_thumbnail.status == "sub"
            %li.list-group-item
              = image_tag(sub_thumbnail.thumbnail.url, class: 'img-responsive')
  -# プロトタイプinfo
  .row.proto-description
    .col-md-3
      %h4 Catch Copy
      %p= @prototype.catch_copy
    .col-md-6
      %h4 Concept
      %p= @prototype.concept
    .col-md-3
      %h4 Tag List
      %ul.proto-tag-list.list-inline
        = render partial: 'tag', collection: @prototype.tags

  -# comment
  .row.proto-comments
    %h4.col-md-12
      Comments
      %span.num= @comments.size
      %br

      = form_tag prototype_comments_path(params[:id]), class: 'form-group', method: :post,   remote: true do
        .col-md-12
          = text_area_tag :content, '', placeholder: 'comment', maxlength: 200, css: 'form-control'
          = hidden_field_tag :prototype_id, params[:id]
          = submit_tag 'comment', class: 'btn btn-primary'
          .comment_content
            = render partial: 'comment', collection: @comments

app/views/tags/_tag.html.haml
.col-sm-4.col-md-3.proto-content
  .thumbnail
    = link_to tag_path(tag) do
      = button_tag "#{tag.name}", class: 'btn btn-tag'
    .tag-meta
      = link_to tag_path(tag), class: 'label label-default tag-list-number' do
        %i "#{tag.taggings.count}" Projects

app/views/tags/index.html.haml
.jumbotron
  .container.text-center
    = image_tag("header_logo.png", alt: 'PROTO TYPE - SHARE THE PROTOTYPE', height: '73px')

= render partial: 'prototypes/sort'

.container.proto-list
  .row
    = render partial: 'tag', collection: @tags

app/views/tags/show.html.haml
.jumbotron
  .container.text-center
    = image_tag("header_logo.png", alt: 'PROTO TYPE - SHARE THE PROTOTYPE', height: '73px')

= render partial: 'prototypes/sort'

.container.proto-list
  .row
    .col-sm-12
      .thumbnail
        = button_tag "#{@tag.name}", class: 'btn btn-tag'
        .tag-meta
          = link_to tag_path(@tag), class: 'label label-default tag-list-number' do
            %i "#{@tag.taggings.count}" Projects

#prototypes
  .container
    .row
      .page
        = render partial: 'prototypes/prototype', collection: @prototypes

= paginate @prototypes

app/views/tags/show.js.erb
$('#prototypes').append("<div class='page'><%= escope_javascript(render partial: 'prototype', collection: @prototypes) %></div>");

app/views/users/_prototype.html.haml
.prototype
  .col-sm-4.col-md-3.proto-content
    .thumbnail
      - if current_user.id == prototype.user_id
        .user_operation
          %ul.operation_list
            %li
              = link_to 'edit', edit_prototype_path(prototype)
            %li
              = link_to 'delete', prototype_path(prototype), method: :delete
      = link_to image_tag(prototype.thumbnails.first.thumbnail.url), prototype_path(prototype)
      .caption
        %h3= prototype.title
        .proto-meta
          .proto-user
            = link_to prototype.user.name, user_path(prototype.user)
          .proto-posted
            = prototype.created_at.strftime('%b %d')
        %ul.proto-tag-list.list-inline
          - prototype.tags.each do |tag|
            %li
              .btn.btn-default= link_to tag.name, tag_path(tag)

app/views/users/show.html.haml
.container.user-page
  %header.user-nav
    .media
      .media-left
        = image_tag(current_user.avatar.url, alt: '64x64', data: { holder: { rendered: 'true' }}, class: 'media-object', style: 'width: 64px; height: 64px;')
      .media-body
        %h4#top-aligned-media.media-heading
          = @user.name
          %span.label.label-default.project-number
            = @user.prototypes.count
            %i Projects
        .proto-user
          %span.degree= @user.name
        .row
          .col-md-6
            %h4 Profile
            %p= @user.profile
          .col-md-6
            %h4 Works
            %p= @user.occupation

#prototypes
  .container
    .row
      .page
        = render partial: 'prototype', collection: @prototypes

= paginate @prototypes